[[Databases]]
database = "shard1"
host = "localhost"
port = 3306

[[Databases]]
database = "shard2"
host = "localhost"
port = 3306
user = "root"
password = ""

[DatabaseCommon]
user = "root"
password = ""
